name: grizzly_notebook
description: Jupyter-like web based environment for interactive computing
version: 0.0.1
homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0
  grizzly_series:
    path: ../grizzly_series
  markd:

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/book/book.dart
      - web/iterable_viewer/iterable_viewer.dart
      - web/array_viewer/array_viewer.dart
      - web/series_viewer/series_viewer.dart
      - web/markdown/markdown_viewer.dart
      - web/dataframe_viewer/dataframe_viewer.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
